name: Update README with recent activity

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # Execute every hour

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README
        run: |
          python update_readme.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}