name: Update README with recent activity

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # Execute every hour

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update README with recent activity
      uses: jamesgeorge007/github-activity-readme@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        COMMIT_NAME: github-actions[bot]
        COMMIT_MSG: Update README with recent activity
        BRANCH: main
        MAX_LINES: 5
        TEMPLATE: default