name: Update README with recent activity

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # Execute every hour

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4