name: Update README with recent activity

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # Execute every hour

jobs:
  update-readme:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
