name: Update README with recent activity

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *' # Execute every hour

jobs:
  build:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update README with activity
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: ":zap: Atualizar README com a atividade recente"
          MAX_LINES: 5
          COMMIT_NAME: GitHub Activity Readme
